package com.mark.mahlola.core.ui.theme

import androidx.compose.ui.graphics.Color

object LightColors {

    val Purple80 = Color(0xFFD0BCFF)
    val PurpleGrey80 = Color(0xFFCCC2DC)
    val Pink80 = Color(0xFFEFB8C8)
    val BACKGROUND_COLOR = Color(0xFFFFF5E8)
    val gradientStartColor=Color(0xFFEE9B27)
    val gradientMiddleColor=Color(0xFFE14D28)
    val gradientEndColor=Color(0xFF6F84B8)
    val Purple40 = Color(0xFF6650a4)
    val PurpleGrey40 = Color(0xFF625b71)
    val Pink40 = Color(0xFF7D5260)
    val background = Color(0xFFFEFBFF)
    val onBackground = Color(0xFF1B1B1F)
    val primary = Color(0xFF005AC1)
    val onPrimary = Color(0xFFFFFFFF)
    val primaryContainer = Color(0xFFD8E2FF)
    val onPrimaryContainer = Color(0xFF001A41)
    val inversePrimary = Color(0xFFADC6FF)
    val secondary = Color(0xFF575E71)
    val onSecondary = Color(0xFFFFFFFF)
    val secondaryContainer = Color(0xFFDBE2F9)
    val onSecondaryContainer = Color(0xFF141B2C)
    val tertiary = Color(0xFF715573)
    val onTertiary = Color(0xFFFFFFFF)
    val tertiaryContainer = Color(0xFFFBD7FC)
    val onTertiaryContainer = Color(0xFF29132D)
    val error = Color(0xFFBA1A1A)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFFFDAD6)
    val onErrorContainer = Color(0xFF410002)
    val surface = Color(0xFFFAF9FD)
    val onSurface = Color(0xFF1B1B1F)
    val surfaceVariant = Color(0xFFE1E2EC)
    val onSurfaceVariant = Color(0xFF44474F)
    val inverseOnSurface = Color(0xFFF2F0F4)
    val inverseSurface = Color(0xFF303033)
    val surfaceTint = Color(0xFF005AC1)
    val outline = Color(0xFF74777F)
    val outlineVariant = Color(0xFFC4C6D0)
    val scrim = Color(0xFF000000)
}